### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by chrissen0814** [yangchaojiang/ZoomPreviewPicture#140]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.previewlibrary.wight.SmoothImageView.transformIn(com.previewlibrary.wight.SmoothImageView$onTransformListener)' on a null object reference
    at com.previewlibrary.view.BasePhotoFragment.transformIn(BasePhotoFragment.java:269)
    at com.previewlibrary.GPreviewActivity$2.onGlobalLayout(GPreviewActivity.java:185)
    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2454)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1530)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7533)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1017)
    at android.view.Choreographer.doCallbacks(Choreographer.java:829)
    at android.view.Choreographer.doFrame(Choreographer.java:764)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1003)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6854)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by yangchaojiang** [comment]
好的，谢谢反馈

**Comment by yangchaojiang** [comment]
下午发布版本

**Comment by yangchaojiang** [comment]
试试2.2.8

**Comment by tomloveyou** [comment]
不行，还是报错
![image](https://user-images.githubusercontent.com/15275230/72499013-b22a6380-386b-11ea-8521-e18407531a15.png)

**Comment by yangchaojiang** [comment]
使用那个版本？

**Comment by yangchaojiang** [comment]
最新的版本 代码行已经不一样

**Comment by tomloveyou** [comment]
2.2.8

**Comment by tomloveyou** [comment]
你居然还没回老家过年，居然还回我了，牛掰啊，大神

**Comment by tomloveyou** [comment]
imageView怎么会报空指针呢，奇怪

**Comment by tomloveyou** [comment]
![image](https://user-images.githubusercontent.com/15275230/72500438-6da0c700-386f-11ea-9881-c2cb01c6d446.png)
也有可能是这个frament为空了

**Comment by tomloveyou** [comment]
这问题不好复现，因为我也是bugly上面看到的，我手机一次都没出现过

**Comment by yangchaojiang** [comment]
你理解错了  是imageView 对象为空。不是frament

**Comment by yangchaojiang** [comment]
2.3.1版本

**Comment by tomloveyou** [comment]
为啥imgview对象会为空呢，照理说已经findviewbyid，又没有把imgview赋值为null，不理解,我太菜了，

**Comment by yangchaojiang** [comment]
释放资源不对，

**Comment by tomloveyou** [comment]
好，感谢大神及时回复我，还及时发版修复

**Comment by sing1ee** [comment]
@yangchaojiang  2.3.1的版本，还有这个问题
```java
Process: com.eboy.etsme, PID: 19140
    java.lang.RuntimeException: Unable to destroy activity {com.eboy.etsme/com.previewlibrary.GPreviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void uk.co.senab2.photoview2.PhotoViewAttacher.setOnViewTapListener(uk.co.senab2.photoview2.PhotoViewAttacher$OnViewTapListener)' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4559)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4578)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void uk.co.senab2.photoview2.PhotoViewAttacher.setOnViewTapListener(uk.co.senab2.photoview2.PhotoViewAttacher$OnViewTapListener)' on a null object reference
        at uk.co.senab2.photoview2.PhotoView.setOnViewTapListener(PhotoView.java:199)
        at com.previewlibrary.view.BasePhotoFragment.release(BasePhotoFragment.java:115)
        at com.previewlibrary.view.BasePhotoFragment.onDestroyView(BasePhotoFragment.java:97)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:2908)
        at androidx.fragment.app.FragmentManager.destroyFragmentView(FragmentManager.java:1370)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1290)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1382)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1460)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2316)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2103)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2058)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1929)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:262)
        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:513)
        at com.previewlibrary.GPreviewActivity.onDestroy(GPreviewActivity.java:70)
        at android.app.Activity.performDestroy(Activity.java:7532)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4544)
```

**Comment by yanghua0726** [comment]
> 好，感谢大神及时回复我，还及时发版修复



> 2.3.1版本

你好，根据我项目上bugly还会出现这个问题， 2.3.5版本。

**Comment by yangchaojiang** [comment]
@yanghua0726 参看demo 代码使用

**Comment by yanghua0726** [comment]
好的谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangchaojiang/ZoomPreviewPicture"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 下午3:34
收件人:&nbsp;"yangchaojiang/ZoomPreviewPicture"<ZoomPreviewPicture@noreply.github.com&gt;;
抄送:&nbsp;"华"<1277231541@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yangchaojiang/ZoomPreviewPicture] 闪退问题 (#140)





 
@yanghua0726 参看demo 代码使用

**Comment by yanghua0726** [comment]
你好，我已经根据demo上的方法进行操作，上线了一段时间观察了bugly，但是还是会出现这个问题，2.3.5的版本。

**Comment by yangchaojiang** [comment]
系统版本是多少

**Comment by yanghuabang05** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangchaojiang/ZoomPreviewPicture"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 中午12:18
收件人:&nbsp;"yangchaojiang/ZoomPreviewPicture"<ZoomPreviewPicture@noreply.github.com&gt;;
抄送:&nbsp;"华"<1277231541@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yangchaojiang/ZoomPreviewPicture] 闪退问题 (#140)





 
系统版本是多少

**Comment by yangchaojiang** [comment]
？？
