### ISSUE TITLE
大量图片预览会崩溃

### ISSUE THREAD

**Issue by snakebang007** [yangchaojiang/ZoomPreviewPicture#149]
android.os.TransactionTooLargeException: data parcel size 1800912 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1147)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3732)

Activity 之间传送的数据量太大，就会崩溃，这个有什么好的解决办法呢

**Comment by yangchaojiang** [comment]
都说了不要加载原图，数据放什么。图片？

**Comment by yangchaojiang** [comment]
大哥大哥，18M的数据，你够厉害的。原生actvity都不支持好么
