### ISSUE TITLE
图片点击崩溃

### ISSUE THREAD

**Issue by solomon2** [yangchaojiang/ZoomPreviewPicture#16]
在“靠谱天天模拟器”上测试demo崩溃， API 19
请大佬看看

`10-09 15:24:18.345 16995-16995/com.example.previewpicture E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.example.previewpicture, PID: 16995
                                                                            android.view.InflateException: Binary XML file line #11: Error inflating class android.widget.ProgressBar
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                                at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                                at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                at com.previewlibrary.PhotoFragment.onCreateView(PhotoFragment.java:52)
                                                                                at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                                                at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                                at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                                at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                                at android.view.View.measure(View.java:16497)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                at android.view.View.measure(View.java:16497)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                at android.view.View.measure(View.java:16497)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                at android.view.View.measure(View.java:16497)
                                                                                at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                                at android.view.View.measure(View.java:16497)
                                                                                at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
                                                                                at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                            	at com.android.internal.os.ZygoteInit.ma
`

**Comment by yangchaojiang** [comment]
谢谢你的反馈，我会尽快修复的

**Comment by yangchaojiang** [comment]
1.1.0 修复
