### ISSUE TITLE
demo 浏览完图片返回闪退报错

### ISSUE THREAD

**Issue by 673195872** [yangchaojiang/ZoomPreviewPicture#161]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void uk.co.senab2.photoview2.PhotoViewAttacher.setOnViewTapListener(uk.co.senab2.photoview2.PhotoViewAttacher$OnViewTapListener)' on a null object reference
        at uk.co.senab2.photoview2.PhotoView.setOnViewTapListener(PhotoView.java:199)
        at com.previewlibrary.view.BasePhotoFragment.release(BasePhotoFragment.java:116)
        at com.previewlibrary.view.BasePhotoFragment.onDestroy(BasePhotoFragment.java:108)
        at android.support.v4.app.Fragment.performDestroy(Fragment.java:2609)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1557)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
        at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:507)
        at com.previewlibrary.GPreviewActivity.onDestroy(GPreviewActivity.java:70)
        at android.app.Activity.performDestroy(Activity.java:6864)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4154)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4185) 
        at android.app.ActivityThread.-wrap6(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by yangjiangs** [comment]
看看最新的版本吧i

**Comment by 673195872** [comment]
就是今天下载的最新版本

**Comment by yangchaojiang** [comment]
好了
你重新pull一下最新的版本，看一下

**Comment by 673195872** [comment]
好的

**Comment by 673195872** [comment]
我项目用重新 加载库  打开浏览图片时  有小圈圈在转 返回 闪退 是因为 库还没同步吗

**Comment by yangchaojiang** [comment]
2.3.4 版本。

**Comment by 673195872** [comment]
好的 谢谢，我看描述上还是 2.3.2版本

**Comment by yangchaojiang** [comment]
摁的啦

**Comment by scorpionfeng** [comment]
请问2.3.4版本修复了这个问题吗 ?  另外2.3.4更新不下来

**Comment by yangchaojiang** [comment]
@scorpionfeng 清除一下缓就行2.3.4 可以拉取的
