### ISSUE TITLE
Canvas: trying to draw too large(110534976bytes) bitmap.

### ISSUE THREAD

**Issue by AndroidKid19** [yangchaojiang/ZoomPreviewPicture#168]
2020-04-06 11:48:27.330 17698-17698/com.fatalsignal.outsourcing.wheel.debug E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.RuntimeException: Canvas: trying to draw too large(110534976bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:151)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1437)
        at com.previewlibrary.wight.SmoothImageView.onDraw(SmoothImageView.java:129)
        at android.view.View.draw(View.java:21636)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21337)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21639)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21337)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21639)
        at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21337)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21639)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.View.draw(View.java:21337)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.updateDisplayListIfDirty(View.java:20465)
        at android.view.View.draw(View.java:21337)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.updateDisplayListIfDirty(View.java:20465)
        at android.view.View.draw(View.java:21337)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4438)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4193)
        at android.view.View.draw(View.java:21639)
        at com.android.internal.policy.DecorView.draw(DecorView.java:922)
        at android.view.View.updateDisplayListIfDirty(View.java:20474)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3722)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3524)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2861)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1808)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7781)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1018)
        at android.view.Choreographer.doCallbacks(Choreographer.java:837)
        at android.view.Choreographer.doFrame(Choreographer.java:767)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1003)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7700)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by yangchaojiang** [comment]
使用什么版本

**Comment by yangchaojiang** [comment]
哥 你图片太大了，麻烦缩小处理呀，bitmap  不支持大的字节
![图片](https://user-images.githubusercontent.com/13806413/78529672-af109500-7814-11ea-8726-974bd4be2014.png)
