### ISSUE TITLE
java.lang.NullPointerException: ... '...SmoothImageView.y(....SmoothImageView$k)' on a null object

### ISSUE THREAD

**Issue by lan2000** [yangchaojiang/ZoomPreviewPicture#187]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.previewlibrary.wight.SmoothImageView.y(com.previewlibrary.wight.SmoothImageView$k)' on a null object reference
    at com.previewlibrary.view.BasePhotoFragment.void transformIn()(BasePhotoFragment.java:263)
    at com.previewlibrary.GPreviewActivity$2.void onGlobalLayout()(GPreviewActivity.java:189)
    at android.view.ViewTreeObserver.null dispatchOnGlobalLayout(null)(ViewTreeObserver.java:945)
    at android.view.ViewRootImpl.null performTraversals(null)(ViewRootImpl.java:2630)
......

**Comment by lan2000** [comment]
左右快速滑动的时候，会不流畅，划不过去。特别是滑动距离不是很长的情况下。

**Comment by yangchaojiang** [comment]
亲故不要直接加载原图，图片文件过大，肯定不流畅

**Comment by lan2000** [comment]
我表达有歧义。是说在快速滑动手指，意图切换下一张图片的时候，偶尔连续滑动几次都切换不成功，回弹当前图片。

**Comment by lan2000** [comment]
另一个错误：

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setEnabled(boolean)' on a null object reference
    at com.previewlibrary.GPreviewActivity$3.void onTransformCompleted(com.previewlibrary.wight.SmoothImageView$Status)(GPreviewActivity.java:215)
    at com.previewlibrary.wight.SmoothImageView$6.void onAnimationEnd(android.animation.Animator)(SmoothImageView.java:419)
    at android.animation.Animator$AnimatorListener.null onAnimationEnd(null)(Animator.java:552)
    at android.animation.ValueAnimator.null endAnimation(null)(ValueAnimator.java:1232)
    at android.animation.ValueAnimator.null doAnimationFrame(null)(ValueAnimator.java:1474)
    at android.animation.AnimationHandler.null doAnimationFrame(null)(AnimationHandler.java:146)

**Comment by lan2000** [comment]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.null get(null)(ArrayList.java:437)
    at com.previewlibrary.GPreviewActivity$2.void onGlobalLayout()(GPreviewActivity.java:188)
    at android.view.ViewTreeObserver.null dispatchOnGlobalLayout(null)(ViewTreeObserver.java:945)
    at android.view.ViewRootImpl.null performTraversals(null)(ViewRootImpl.java:2391)
    at android.view.ViewRootImpl.null doTraversal(null)(ViewRootImpl.java:1520)
    at android.view.ViewRootImpl$TraversalRunnable.null run(null)(ViewRootImpl.java:7004)
    at android.view.Choreographer$CallbackRecord.null run(null)(Choreographer.java:1059)
    at android.view.Choreographer.null doCallbacks(null)(Choreographer.java:871)

**Comment by ooftf** [comment]
Attempt to invoke virtual method 'void com.previewlibrary.wight.SmoothImageView.transformIn(com.previewlibrary.wight.SmoothImageView$onTransformListener)' on a null object reference

**Comment by ooftf** [comment]
这个问题我也遇到了，应该在transformIn内的imageView做个非空判断

**Comment by pz-bottle** [comment]
兄弟们请问解决了吗？我现在还有这个问题

**Comment by yangchaojiang** [comment]
@pz-bottle @ooftf   2.3.7  @lan2000 @protectedMan

**Comment by zhangmeie** [comment]
> @pz-bottle @ooftf 2.3.7 @lan2000 @protectedMan
compile 'com.ycjiang:ImagePreview:2.3.7' 版本也遇到了
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.previewlibrary.GPreviewActivity$2.onGlobalLayout(GPreviewActivity.java:188)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1066)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3318)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2235)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9043)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
