### ISSUE TITLE
 java.lang.NullPointerException: loader no init

### ISSUE THREAD

**Issue by jounghu** [yangchaojiang/ZoomPreviewPicture#46]
1，九宫格我用的是传递的是List `<String>`
```java

  private List<ThumbViewInfo> computeBoundsBackward(List list) {
            List<ThumbViewInfo> thumbViewInfos = new ArrayList<>();
            for (int i = 0; i < activeNglIv.getChildCount(); i++) {
                View item = activeNglIv.getChildAt(i);
                Rect bounds = new Rect();
                if (item != null) {
                    ImageView thumbView = (ImageView) item;
                    thumbView.getGlobalVisibleRect(bounds);
                }
                ThumbViewInfo viewInfo = new ThumbViewInfo((String) list.get(i));
                viewInfo.setmBounds(bounds);
                thumbViewInfos.add(viewInfo);
            }
            return thumbViewInfos;
        }

```

然后我将返回的 thumbViewInfos 放进去，点击图片预览

```log

                                                                                       java.lang.NullPointerException: loader no init
                                                                                           at com.previewlibrary.ZoomMediaLoader.getLoader(ZoomMediaLoader.java:34)
                                                                                           at com.previewlibrary.view.BasePhotoFragment.initDate(BasePhotoFragment.java:169)
                                                                                           at com.previewlibrary.view.BasePhotoFragment.onViewCreated(BasePhotoFragment.java:73)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                                           at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                           at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                                           at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                                           at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                                           at android.view.View.measure(View.java:16497)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                           at android.view.View.measure(View.java:16497)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                           at android.view.View.measure(View.java:16497)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                           at android.view.View.measure(View.java:16497)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                                           at android.view.View.measure(View.java:16497)
                                                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
                                                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
                                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
                                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
                                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
                                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                           at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                           at android.os.Handler.handleCallback(Handler.java:733)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5019)
                                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                           at dalvik.system.NativeStart.main(Native Method)


```

**Comment by yangchaojiang** [comment]
你没有初始化，imageload哦

**Comment by jounghu** [comment]
@yangchaojiang 我按照你的nine demo写的，imageload在哪初始化？ 

这是我按照你的写法，把我构造的thumbViewInfos 放进去的，
```java
   GPreviewBuilder.from((Activity) context)
                            .setData(thumbViewInfos)
                            .setCurrentIndex(index)
                            .setType(GPreviewBuilder.IndicatorType.Dot)
                            .start();//启动

```

**Comment by yangchaojiang** [comment]
看demo，applicstion，oncreate方法

**Comment by jounghu** [comment]
@yangchaojiang  谢谢大神回复（本人菜鸟，别见怪 ):  ）

**Comment by yangchaojiang** [comment]
谢谢支持哈，记得star😃 😃 😃
