### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by langxing** [yangchaojiang/ZoomPreviewPicture#95]
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.Activity.onCreate(Activity.java:993)
        at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:285)
        at com.previewlibrary.GPreviewActivity.onCreate(GPreviewActivity.java:55)
        at com.example.previewpicture.custom.CustomActivity.onCreate(CustomActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:6986)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1232)

**Comment by langxing** [comment]
我查了google，去掉android:screenOrientation="portrait"，就可以了

**Comment by yangchaojiang** [comment]
是新版已经没有，更新你的版本
